import { ArrowLeft, FileText, ShieldCheck } from "lucide-react";
import { Link, useLocation } from "wouter";

const content = {
  terms: {
    en: { label: "TERMS OF USE", title: "A clear agreement for learning well.", intro: "These terms explain how visitors may use medical.sketcher, its learning materials, book previews, assessments and Instagram-based order contact.", sections: [["Using the platform", "Use the website lawfully and respectfully. Do not copy, resell, redistribute or publicly upload paid or restricted learning materials without written permission."], ["Book requests", "Book requests are handled through the listed Instagram account. Price, delivery method and availability should be confirmed in the conversation before any payment or delivery."], ["Learning content", "Assessments are educational tools and do not represent a professional language certification unless a separate certificate is explicitly issued by the platform."], ["Changes", "We may update sections, materials or these terms as the platform develops. The latest version will be shown on this page."]], note: "Working draft — review with a qualified local lawyer before relying on this page for a commercial launch." },
    de: { label: "NUTZUNGSBEDINGUNGEN", title: "Ein klarer Rahmen für gutes Lernen.", intro: "Diese Bedingungen erklären die Nutzung von medical.sketcher, Lernmaterialien, Leseproben, Tests und Bestellanfragen über Instagram.", sections: [["Nutzung der Plattform", "Die Website ist rechtmäßig und respektvoll zu nutzen. Lernmaterialien dürfen ohne schriftliche Erlaubnis nicht kopiert, weiterverkauft oder öffentlich verbreitet werden."], ["Buchanfragen", "Buchanfragen werden über das angegebene Instagram-Konto bearbeitet. Preis, Lieferung und Verfügbarkeit müssen vor Zahlung oder Lieferung im Chat bestätigt werden."], ["Lerninhalte", "Die Tests dienen dem Lernen und sind keine professionelle Sprachzertifizierung, sofern die Plattform nicht ausdrücklich ein Zertifikat ausstellt."], ["Änderungen", "Wir können Inhalte, Materialien oder diese Bedingungen weiterentwickeln. Die aktuelle Fassung steht auf dieser Seite."]], note: "Arbeitsentwurf — vor einem kommerziellen Start durch eine qualifizierte lokale Rechtsberatung prüfen lassen." },
    ar: { label: "شروط الاستخدام", title: "إطار واضح لتجربة تعلم أفضل.", intro: "توضح هذه الشروط طريقة استخدام medical.sketcher ومواده التعليمية والمعاينات والاختبارات وطلبات الكتب عبر Instagram.", sections: [["استخدام المنصة", "استخدم الموقع بطريقة قانونية ومحترمة. لا تنسخ المواد التعليمية أو تعيد بيعها أو تنشرها علنًا من دون إذن كتابي."], ["طلبات الكتب", "تتم طلبات الكتب عبر حساب Instagram الموضح في الموقع. يجب تأكيد السعر وطريقة التسليم والتوفر في المحادثة قبل أي دفع أو تسليم."], ["المحتوى التعليمي", "الاختبارات أدوات تعليمية وليست شهادة لغة مهنية، إلا إذا أعلنت المنصة صراحة عن إصدار شهادة مستقلة."], ["التعديلات", "قد نحدّث الأقسام أو المواد أو هذه الشروط مع تطور المنصة، وستظهر النسخة الأحدث في هذه الصفحة."]], note: "مسودة عمل — راجعها مع محامٍ مؤهل في بلدك قبل الاعتماد عليها عند الإطلاق التجاري." },
  },
  privacy: {
    en: { label: "PRIVACY POLICY", title: "Your learning journey stays considered.", intro: "This page describes the privacy principles for medical.sketcher. Keep it aligned with the tools, accounts and data actually used by the platform.", sections: [["Information you provide", "You may provide account details when signing in, and contact details when you send an Instagram order message. Only share information needed to receive support or a book."], ["How information is used", "Information may be used to provide the platform, respond to requests, secure accounts, improve learning experiences and maintain the service."], ["Third parties", "Instagram handles the conversation after you follow the order link. Its own privacy policy and terms apply to activity on Instagram."], ["Your choices", "You can ask about information associated with your account or request correction where applicable. Avoid sending health records or other sensitive information through the learning assistant."]], note: "Working draft — review with a qualified local lawyer and align this policy with your hosting, analytics, authentication and messaging providers." },
    de: { label: "DATENSCHUTZERKLÄRUNG", title: "Dein Lernweg bleibt bewusst gestaltet.", intro: "Diese Seite beschreibt die Datenschutzgrundsätze von medical.sketcher. Sie muss mit den tatsächlich eingesetzten Konten, Tools und Daten abgeglichen werden.", sections: [["Bereitgestellte Informationen", "Bei der Anmeldung können Kontodaten und bei einer Instagram-Anfrage Kontaktdaten übermittelt werden. Teile nur Informationen, die für Hilfe oder eine Bestellung notwendig sind."], ["Verwendung", "Daten können für den Betrieb der Plattform, Antworten auf Anfragen, Kontosicherheit, Lernerfahrung und Wartung verwendet werden."], ["Dritte", "Instagram übernimmt die Unterhaltung, sobald du dem Bestelllink folgst. Für Instagram gelten dessen eigene Datenschutzbedingungen."], ["Deine Möglichkeiten", "Du kannst nach den zu deinem Konto gehörenden Informationen fragen oder gegebenenfalls eine Korrektur anfordern. Sende dem Lernassistenten keine Gesundheitsakten."]], note: "Arbeitsentwurf — mit lokaler Rechtsberatung prüfen und an Hosting-, Analyse-, Login- und Messaging-Dienste anpassen." },
    ar: { label: "سياسة الخصوصية", title: "خصوصيتك جزء من تجربة التعلم.", intro: "توضح هذه الصفحة مبادئ الخصوصية في medical.sketcher، ويجب مواءمتها مع الأدوات والحسابات والبيانات المستخدمة فعليًا في المنصة.", sections: [["المعلومات التي تقدمها", "قد تقدم بيانات حسابك عند تسجيل الدخول، وبيانات التواصل عند إرسال طلب عبر Instagram. شارك فقط المعلومات اللازمة للمساعدة أو استلام الكتاب."], ["طريقة الاستخدام", "قد تُستخدم المعلومات لتشغيل المنصة، والرد على الطلبات، وتأمين الحسابات، وتحسين تجربة التعلم، والحفاظ على الخدمة."], ["الخدمات الخارجية", "يتولى Instagram المحادثة بعد الضغط على رابط الطلب، وتطبق على نشاطك هناك سياسة الخصوصية وشروط Instagram الخاصة به."], ["خياراتك", "يمكنك الاستفسار عن المعلومات المرتبطة بحسابك أو طلب تصحيحها حيثما ينطبق. لا ترسل سجلات صحية أو معلومات حساسة إلى المساعد التعليمي."]], note: "مسودة عمل — راجعها مع محامٍ مؤهل ومواءمتها مع مزودي الاستضافة والتحليلات وتسجيل الدخول والرسائل." },
  },
} as const;

export default function LegalPage({ type }: { type: "terms" | "privacy" }) {
  const [location] = useLocation();
  const locale = location.includes("/ar/") ? "ar" : location.includes("/de/") ? "de" : "en";
  const page = content[type][locale];
  return <main className="min-h-screen bg-[#f7f4eb] text-[#1d281c]" dir={locale === "ar" ? "rtl" : "ltr"}><header className="border-b border-[#253c2a]/10 bg-[#fffdf7]"><div className="mx-auto flex max-w-4xl items-center justify-between px-5 py-5"><Link href="/" className="inline-flex items-center gap-2 text-sm font-semibold text-[#536d37]"><ArrowLeft className="size-4 rtl:rotate-180" /> medical.sketcher</Link><span className="rounded-full bg-[#e8edcf] px-3 py-1 text-xs font-bold tracking-[.12em] text-[#536d37]">{type === "terms" ? <FileText className="mr-1 inline size-3" /> : <ShieldCheck className="mr-1 inline size-3" />}{page.label}</span></div></header><article className="mx-auto max-w-4xl px-5 py-16 sm:py-24"><p className="text-xs font-bold tracking-[.18em] text-[#89966d]">medical.sketcher · {page.label}</p><h1 className="mt-5 max-w-3xl font-display text-4xl font-bold leading-tight sm:text-6xl">{page.title}</h1><p className="mt-6 max-w-2xl text-base leading-8 text-[#667064]">{page.intro}</p><div className="mt-12 grid gap-4">{page.sections.map(([heading, body]) => <section key={heading} className="rounded-[1.5rem] border border-[#253c2a]/10 bg-white p-6 shadow-sm sm:p-8"><h2 className="font-display text-2xl font-bold">{heading}</h2><p className="mt-3 leading-7 text-[#667064]">{body}</p></section>)}</div><p className="mt-8 rounded-2xl bg-[#f1e5cf] p-5 text-sm leading-6 text-[#76592f]">{page.note}</p></article></main>;
}
